version: '3.8'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"

  running:
    image: postgres
    container_name: "running"
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/running_db_password
    ports:
      - "5432:5432"
    secrets:
      - running_db_password

secrets:
  running_db_password:
    file: ~/play/secrets/running_db_password.txt
